-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 26-02-2020 a las 23:33:05
-- Versión del servidor: 10.4.8-MariaDB
-- Versión de PHP: 7.3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `noticias`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `articulo`
--

CREATE TABLE `articulo` (
  `id` int(100) NOT NULL,
  `link` varchar(200) NOT NULL,
  `titulo` varchar(500) NOT NULL,
  `autor` varchar(200) NOT NULL,
  `fecha` varchar(50) NOT NULL,
  `descripcion` varchar(500) NOT NULL,
  `id_pagina` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `articulo`
--

INSERT INTO `articulo` (`id`, `link`, `titulo`, `autor`, `fecha`, `descripcion`, `id_pagina`) VALUES
(83, 'https://es.gizmodo.com/nintendo-acude-al-rescate-despues-de-que-a-una-abuela-d-1841917900', 'Nintendo acude al rescate después de que a una abuela de 95 años se le rompiera su Game Boy', 'Andrew Liszewski', '23:31:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--76SXLPrr--/c_fit,fl_progressive,q_80,w_636/twmwkzzftgfly1mqkkiy.jpg\"><p>Nintendo es conocida por su excelente servicio al cliente, pero de vez en cuando la compañía también va mas allá del llamado del deber en casos muy especiales. Cuando los técnicos no pudieron arreglar el <a href=\"https://es.gizmodo.com/relajate-con-este-fantastico-video-en-el-que-restauran-1835198178\">Game Boy original</a> de una mujer japonesa de 95 años, la com', 10),
(84, 'https://es.gizmodo.com/youporn-ha-lanzado-una-version-porno-de-tiktok-llamada-1841916427', 'YouPorn ha lanzado una versión porno de TikTok llamada SWYP', 'Whitney Kimball', '22:37:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--LPsUvfHm--/c_fit,fl_progressive,q_80,w_636/kjutnyjufb4btiudkpfu.jpg\"><p>Todo acaba teniendo una versión porno. Hay versiones porno de YouTube; versiones porno de <a href=\"https://venturebeat.com/2018/09/25/youporn-launches-personalized-weekly-video-playlists-powered-by-machine-learning/\" target=\"_blank\" rel=\"noopener noreferrer\">Spotify</a>; y por fin, después de un retraso sorprendentemente largo, si lo piensas, una versión porno de', 10),
(85, 'https://es.gizmodo.com/esta-crema-de-cacahuete-es-un-recordatorio-de-que-estam-1841914904', 'Esta crema de cacahuete es un recordatorio de que estamos pronunciando mal la palabra \"GIF\"', 'Matías S. Zavia', '21:59:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--tjvq2Gdg--/c_fit,fl_progressive,q_80,w_636/cazrw5dmhkifhufgnshc.jpg\"><p>El 1 de marzo es el Día de los Amantes de la Crema de Cacahuete (según <a href=\"https://nationaldaycalendar.com/national-peanut-butter-lovers-day-march-1/\" target=\"_blank\" rel=\"noopener noreferrer\">una web</a> de festividades inventadas) y la marca Jif lo está celebrando con una campaña publicitaria junto a GIPHY, el famoso buscador de GIFs animados. La singular ', 10),
(86, 'https://es.gizmodo.com/no-descartan-cancelar-los-juegos-olimpicos-de-tokio-202-1841913262', 'No descartan cancelar los Juegos Olímpicos de Tokio 2020 por el coronavirus', 'Eduardo Marín', '20:01:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--xY0pBw38--/c_fit,fl_progressive,q_80,w_636/os9cwx5tni912pic6u5u.jpg\"><p>Se espera que a finales del mes de julio den inicio los Juegos Olímpicos de 2020, que esta vez se llevarán a cabo en la capital de Japón. Sin embargo, el aumento de casos del <a href=\"https://es.gizmodo.com/cada-vez-parece-mas-dificil-detener-el-coronavirus-1841840960\">coronavirus</a> en todo el mundo, incluyendo el territorio nipón, podrían llevar a la cancelaci', 10),
(87, 'https://es.gizmodo.com/el-majestuoso-vuelo-de-un-buho-a-traves-de-miles-de-bur-1841907719', 'El majestuoso vuelo de un búho a través de miles de burbujas esconde el secreto para diseñar mejores aviones', 'Carlos Zahumenszky', '16:25:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--ftPP2P8V--/c_fit,fl_progressive,q_80,w_636/kjbjftvxnh7ygw46nlkk.gif\"><p>Al principio no se ve nada. Solo una habitación oscura. De repente, un búho pasa volando y el aire se ilumina con miles de pequeñas partículas que se arremolinan en el aire al paso del ave. Poco a poco, las burbujas forman dos vórtices perfectos que esconden un truco muy interesante.<br></p><p><a href=\"https://es.gizmodo.com/el-majestuoso-vuelo-de-un-buho-a-trave', 10),
(88, 'https://es.gizmodo.com/el-momento-exacto-en-el-que-miles-de-camarones-reaccion-1841906678', 'El momento exacto en el que miles de camarones reaccionan a un temblor que acaba de producirse a 160 kilómetros', 'Miguel Jorge', '15:42:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--ZGdWwEV5--/c_fit,fl_progressive,q_80,w_636/zyh0r9ck8qeccohwr0jt.gif\"><p>La <a href=\"https://www.youtube.com/watch?v=Ho1E8A6zGWg&amp;feature=emb_title\" target=\"_blank\" rel=\"noopener noreferrer\">escena</a> ocurrió a comienzos de 2020, cuando un robot explorador lanzado por la Institución Oceanográfica de Woods Hole capturó un evento inusual y salvaje a lo largo de una cresta montañosa en las profundidades del mar del Caribe.<br></p><p>', 10),
(89, 'https://es.gizmodo.com/este-chevrolet-electrico-cuesta-20-000-euros-y-tiene-41-1841904932', 'Este Chevrolet eléctrico cuesta 20.000 euros y tiene 410 km de autonomía, pero probablemente no puedas comprarlo', 'Miguel Jorge', '14:13:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--4om15vxx--/c_fit,fl_progressive,q_80,w_636/fg2zdsmnccspuexcptgs.jpg\"><p>Para aquellos que están buscando comprar su primer auto 100% eléctrico, el Chevrolet Menlo posiblemente sería perfecto. Su precio ronda los 20.000 euros, sus características son de lo más punteras, e incluso cuenta con una autonomía de 410 kilómetros. Y sin embargo, GM no va <a href=\"https://electrek.co/2020/02/24/gm-menlo-electric-car-range-price/\" target=\"_blan', 10),
(90, 'https://es.gizmodo.com/este-pajaro-muerto-perfectamente-conservado-ha-aparecid-1841904297', 'Este pájaro perfectamente conservado en el hielo de Siberia tiene más de 44.000 años', 'Carlos Zahumenszky', '13:27:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--ekAMkFvM--/c_fit,fl_progressive,q_80,w_636/tuoerr5aazcecldkucto.png\"><p>Un grupo de buscadores de marfil fosilizado de la localidad de Belaya Gora, al norte de Rusia, ha desenterrado del permafrost un auténtico tesoro para la ciencia. Se trata de un pajarito muerto de una especia extinta hace más de 44.000 mil años pero cuyo cuerpo está excepcionalmente conservado.<br></p><p><a href=\"https://es.gizmodo.com/este-pajaro-muerto-perfecta', 10),
(91, 'https://es.gizmodo.com/una-mujer-inhala-550-veces-la-dosis-habitual-de-lsd-cre-1841903895', 'Una mujer inhala 550 veces la dosis habitual de LSD creyendo que era cocaína. Esto fue lo que pasó', 'Miguel Jorge', '12:53:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--WxWGg0KI--/c_fit,fl_progressive,q_80,w_636/ai4rxkhnfzmtiapac0tk.jpg\"><p>¿Qué ocurre cuando alguien ingiere accidentalmente 10 veces la dosis recreativa <em>normal</em> de LSD? ¿Y si elevamos esa dosis <a href=\"https://www.iflscience.com/health-and-medicine/woman-accidentally-snorts-550-times-usual-dose-of-lsd-in-one-go-this-is-what-happened/\" target=\"_blank\" rel=\"noopener noreferrer\">hasta 550 veces</a>? Un nuevo estudio detalla tres', 10),
(92, 'https://es.gizmodo.com/nuevos-heroes-y-nuevos-villanos-bienvenidos-a-la-fase-1841902890', 'Nuevos héroes y nuevos villanos: Bienvenidos a la Fase 1 del futuro universo Star Wars: The High Republic', 'Carlos Zahumenszky', '11:23:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--TMRT3cG5--/c_fit,fl_progressive,q_80,w_636/sqcgiul8dr7gapdb5jqw.jpg\"><p>Disney se tomó muchas molestias en señalar que <em>The Rise of Skywalker</em> era el fin de una era para Star Wars. Con el final de la trilogía aún en los cines, la compañía dió a conocer sus planes para la franquicia con algo llamado <em>Project Luminous</em>. Ahora sabemos su nombre definitivo: <em>Star Wars: The High Republic</em>.<br></p><p><a href=\"https://e', 10),
(93, 'https://es.gizmodo.com/un-granjero-descubre-una-roca-en-turquia-y-esa-roca-ha-1841902702', 'Un granjero descubre una roca en Turquía, y esa roca ha revelado un misterioso reino perdido en la historia', 'Miguel Jorge', '11:06:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--yPghxh21--/c_fit,fl_progressive,q_80,w_636/fzxfopbdc3iknmwudny7.jpg\"><p>Como ocurre en tantas ocasiones con este tipo de hallazgos, todo empezó de forma fortuita. Un agricultor turco descubre una mañana <a href=\"https://www.sciencealert.com/giant-mound-in-turkey-discovered-to-be-mysterious-ancient-kingdom-lost-in-history\" target=\"_blank\" rel=\"noopener noreferrer\">una gran piedra inscrita</a> mientras dragaba un canal de riego cercano', 10),
(94, 'https://es.gizmodo.com/un-estadounidense-que-regreso-de-china-tras-el-coronavi-1841901890', 'Un estadounidense que regresó de China tras el coronavirus debe pagar miles de dólares por hacerse una prueba de la gripe', 'Tom McKay', '09:33:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--e2LHUdYP--/c_fit,fl_progressive,q_80,w_636/pwzq2bizugpxuwlzdo9p.jpg\"><p>Un hombre de Miami que se sintió enfermo después de regresar de un viaje de negocios a China el pasado mes de enero recibió una factura de 3.270 dólares por asegurarse y hacerse una prueba para determinar si estaba infectado con el coronavirus de Wuhan, informó el lunes <a href=\"https://www.miamiherald.com/news/health-care/article240476806.html\" target=\"_blank\" r', 10),
(95, 'https://es.gizmodo.com/como-activar-la-barra-de-herramientas-oculta-que-chrome-1841901760', 'Cómo activar la barra de herramientas oculta que Chrome tiene en Android', 'Brendan Hesse', '09:17:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--6-rIRqfb--/c_fit,fl_progressive,q_80,w_636/nwbmjdysmq1sn0mfefsd.jpg\"><p>Los navegadores web tienen la barra de dirección y los controles en la parte superior de la pantalla. No es lo mejor cuando trabajamos en un móvil con una pantalla grande. Algunos navegadores como Firefox Preview, Vivaldi o Chrome tienen la opción de poner los controles en la parte inferior. Espera... ¿Chrome?</p><p><a href=\"https://es.gizmodo.com/como-activar-la', 10),
(96, 'https://es.gizmodo.com/realme-x50-pro-5g-snapdragon-865-pantalla-de-90hz-y-c-1841898119', 'Realme X50 Pro 5G: Snapdragon 865, pantalla de 90Hz y carga de 65W por 600€', 'Matías S. Zavia', '04:07:00 2020-02-25', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--ogVodyyv--/c_fit,fl_progressive,q_80,w_636/tdbmqndoarf3hmyyinfb.jpg\"><p>Realme ha presentado este lunes su nuevo buque insignia, un smartphone 5G con el último procesador de Qualcomm y la memoria más rápida disponible. Sobre el papel, el Realme X50 Pro 5G coloca a la marca a la altura de competidores como <a href=\"https://es.gizmodo.com/el-nuevo-xiaomi-mi-10-tiene-una-camara-de-108-mp-panta-1841669910\">Xiaomi</a> y <a href=\"https://e', 10),
(97, 'https://es.gizmodo.com/este-tesla-model-x-ha-recorrido-mas-de-640-000-kilometr-1841890486', 'Este Tesla Model X ha recorrido más de 640.000 kilómetros. Estas son todas las reparaciones que hubo que hacerle', 'David Tracy', '19:49:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--FIZ3Wif8--/c_fit,fl_progressive,q_80,w_636/ibegalpt6ujln732995b.jpg\"><p>Hace poco, vendieron en la página <a href=\"https://onlyusedtesla.com/listing/model-x-2016-midnight-silver-metallic-0c922/\" target=\"_blank\" rel=\"noopener noreferrer\">Only Used Tesla</a> el que se cree que es el <a href=\"https://jalopnik.com/tag/tesla-model-x\" target=\"_blank\" rel=\"noopener noreferrer\">Tesla Model X</a> con más kilómetros del mundo: un coche/lanzade', 10),
(98, 'https://es.gizmodo.com/como-es-usar-el-huawei-mate-30-pro-con-y-sin-google-ser-1841827756', 'Cómo es usar el Huawei Mate 30 Pro con y sin Google Services (y por qué deberías instalarlos)', 'Carlos Zahumenszky', '19:09:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--FwuNPrbl--/c_fit,fl_progressive,q_80,w_636/k5lh27woal1peihgmvls.jpg\"><p>En algunos países fugarse de prisión no es un delito en sí mismo porque buscar la libertad se considera algo inherente a la naturaleza humana. De igual manera, los prisioneros de guerra suelen considerar la fuga como una obligación. Cuando encendí por primera vez el Huawei Mate 30 Pro  supe lo que debía hacer.<br></p><p><a href=\"https://es.gizmodo.com/como-es-usa', 10),
(99, 'https://es.gizmodo.com/microsoft-revela-nuevos-detalles-sobre-la-xbox-series-x-1841889110', 'Microsoft revela nuevos detalles sobre la Xbox Series X y su insólita potencia', 'Sam Rutherford', '18:10:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--JpqMeBVo--/c_fit,fl_progressive,q_80,w_636/sw7rfdp7igwnwe8afohx.jpg\"><p>Aunque sigue guardándose información para el E3 de junio, Microsoft ha <a href=\"https://news.xbox.com/en-us/2020/02/24/what-you-can-expect-next-generation-gaming/\" target=\"_blank\" rel=\"noopener noreferrer\">publicado nuevos detalles</a> sobre su próxima consola insignia: la Xbox Series X.</p><p><a href=\"https://es.gizmodo.com/microsoft-revela-nuevos-detalles-sobre', 10),
(100, 'https://es.gizmodo.com/la-alarmante-diferencia-que-existe-cuando-estrellas-un-1841886031', 'La alarmante diferencia que existe cuando estrellas un Nissan fabricado en Europa contra uno fabricado en Sudáfrica', 'Miguel Jorge', '15:46:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--WvRzW2rk--/c_fit,fl_progressive,q_80,w_636/uvxjrixlr9yv7p30shqo.gif\"><p>Global NCAP, el programa de evaluación de la seguridad de los vehículos respaldado por la Unión Europea, ha lanzado recientemente un vídeo donde chocan frontalmente el modelo de pick-up más vendido en África, el Nissan NP300 Hardbody 2019, con un Nissan Navara de segunda mano fabricado en Europa. Las diferencias <a href=\"https://www.youtube.com/watch?v=UL_2MdSTM7', 10),
(101, 'https://es.gizmodo.com/este-camion-de-290-toneladas-sera-el-vehiculo-electrico-1841884404', 'Este camión de 290 toneladas será el vehículo eléctrico más grande del mundo', 'Miguel Jorge', '13:43:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--lzSGuffg--/c_fit,fl_progressive,q_80,w_636/rnehqcreuu3nka1iucy9.jpg\"><p>La compañía Anglo American, con sede en Londres, está desarrollando una auténtica bestia en forma de camión como parte de su visión minera sostenible. El resultado se llama Fuel Cell, el <a href=\"https://www.businessinsider.com/new-worlds-largest-electric-vehicle-is-290-ton-dump-truck-2020-2?r=US&amp;IR=T#the-new-hydrogen-project-is-a-part-of-the-anglo-americans-', 10),
(102, 'https://es.gizmodo.com/disney-abre-su-suscripcion-anual-en-europa-con-un-desc-1841883257', 'Disney+ abre su suscripción anual en Europa con un descuento por tiempo limitado', 'Miguel Jorge', '11:17:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--P47bD3uc--/c_fit,fl_progressive,q_80,w_636/dnfpfrel6eajyc0ienwj.jpg\"><p>Al igual que ocurrió en Estados Unidos antes de lanzarse, Disney ha abierto las suscripciones anuales de Disney+ en Europa con <a href=\"https://www.engadget.com/2020/02/24/disney-plus-europe-discount-deal-launch/\" target=\"_blank\" rel=\"noopener noreferrer\">una jugosa oferta</a>. Los usuarios que se apunten de aquí  al 23 de marzo tendrán un descuento de 10 euros.<', 10),
(103, 'https://es.gizmodo.com/un-nuevo-informe-afirma-que-dos-tercios-de-los-casos-mu-1841883114', 'Un nuevo informe afirma que dos tercios de los casos mundiales de coronavirus han pasado desapercibidos', 'Miguel Jorge', '10:59:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--BdkgUEUu--/c_fit,fl_progressive,q_80,w_636/uspkkzgjmrm4oitg5go8.jpg\"><p>Hace unos días los investigadores chinos <a href=\"https://www.businessinsider.com/coronavirus-asymptomatic-transmission-chinese-woman-relatives-2020-2?r=US&amp;IR=T\" target=\"_blank\" rel=\"noopener noreferrer\">confirmaron</a> que una persona puede transportar y transmitir el coronavirus COVID-19 sin mostrar síntomas. Ahora, un estudio del Imperial College de Londre', 10),
(104, 'https://es.gizmodo.com/xperia-1-ii-el-nuevo-smartphone-de-sony-coge-algunas-d-1841883090', 'Xperia 1 II: el nuevo smartphone de Sony coge algunas de las grandes funciones de sus cámaras de gama alta', 'Sam Rutherford', '10:57:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--U8ECkgXy--/c_fit,fl_progressive,q_80,w_636/pyvubswrannbinpbkrgr.jpg\"><p>A pesar de que el <a href=\"https://es.gizmodo.com/es-oficial-la-gsma-cancela-el-mobile-world-congress-de-1841630911\">MWC 2020 haya sido cancelado</a>, Sony todavía sigue haciendo avances. Hoy, la compañía ha presentado un nuevo miembro de su familia de smartphones: el Xperia 1 II.</p><p><a href=\"https://es.gizmodo.com/xperia-1-ii-el-nuevo-smartphone-de-sony-coge-', 10),
(105, 'https://es.gizmodo.com/nadie-sabe-por-que-un-npc-aleatorio-en-red-dead-redempt-1841882350', 'Nadie sabe por qué un NPC aleatorio en Red Dead Redemption II se convirtió repentinamente en un asesino', 'Zack Zwiezen', '09:28:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--mwQexRhB--/c_fit,fl_progressive,q_80,w_636/ruwgefbtrux7rnwafvuj.gif\"><p>He jugado mucho a <em>Red Dead Redemption II</em> y al modo multijugador online. En este punto, he invertido cientos y cientos de horas. Y he visto muchas cosas extrañas, geniales y malas. Con todo, no he visto nada como lo que un jugador compartió en el subreddit RDR2 hace unos días.<br></p><p><a href=\"https://es.gizmodo.com/nadie-sabe-por-que-un-npc-aleatorio-e', 10),
(106, 'https://es.gizmodo.com/google-pide-a-los-usuarios-de-moviles-huawei-que-no-ins-1841882301', 'Google pide a los usuarios de móviles Huawei que no instalen Google Apps desde servicios de terceros', 'Jody Serrano', '09:22:00 2020-02-24', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--Hk34sULh--/c_fit,fl_progressive,q_80,w_636/gjd3z3daesp6jbqza4vf.jpg\"><p>Google ha querido dejar las cosas claras a los usuarios de Huawei: los servicios de Google no pueden precargarse en nuevos dispositivos debido a las restricciones impuestas por el gobierno de Estados Unidos. Si tratas de hacerlo mediante otro método diferente a la Play Store pueden pasar cosas malas.</p><p><a href=\"https://es.gizmodo.com/google-pide-a-los-usuario', 10),
(107, 'http://feeds.weblogssl.com/~r/xataka2/~3/zYYxEEkhGPM/bob-iger-dimite-como-ceo-disney-efecto-inmediato-sera-reemplazado-bob-chapek', 'Bob Iger dimite como CEO de Disney con efecto inmediato, será reemplazado por Bob Chapek', 'Cristian Rus', '23:04:58 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/7ad295/adaf55db-ca27-4ada-b031-ff2f9f4e960b/1024_2000.jpeg\" alt=\"Bob Iger dimite como CEO de Disney con efecto inmediato, será reemplazado por Bob Chapek\">\n    </p>\n    <p>Disney cambia de CEO, <strong>Bob Iger</strong>, que ha estado en el cargo durante los últimos 15 años, <strong>ha dimitido</strong>. Será reemplazado por <a href=\"https://thewaltdisneycompany.com/leaders/bob-chapek/\">Bob Chapek</a>, el actual responsable de Parques, Experiencias y Produc', 11),
(108, 'http://feeds.weblogssl.com/~r/xataka2/~3/vfcS6rz1QI8/amazon-abre-su-primer-go-grocery-supermercado-cajeros-cinco-veces-grande-que-tiendas-amazon-go', 'Amazon abre su primer Go Grocery: un supermercado sin cajeros y hasta cinco veces mas grande que las tiendas Amazon Go', 'Cristian Rus', '20:52:43 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/0baa91/39f95492-38ee-4f16-92e1-ba5161f4a958/1024_2000.jpeg\" alt=\"Amazon abre su primer Go Grocery: un supermercado sin cajeros y hasta cinco veces mas grande que las tiendas Amazon Go\">\n    </p>\n    <p>Amazon <a href=\"https://www.xataka.com/robotica-e-ia/asi-funciona-la-primera-tienda-fisica-de-amazon-sin-cajas-y-casi-sin-empleados\">sorprendió a todo el mundo</a> hace unos años al anunciar su primera tienda Amazon Go sin cajeros en la que sales \"sin pagar\".', 11),
(109, 'http://feeds.weblogssl.com/~r/xataka2/~3/xLXgRbCwqTA/huawei-matepad-pro-primeras-impresiones-opiniones-video-fotos', 'Huawei MatePad Pro, primeras impresiones: una clara apuesta por el software propio y adaptado al formato tablet', 'Anna Martí', '17:35:03 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/47c63c/huawei-mediapad-pro-naranja-trasera-01/1024_2000.jpg\" alt=\"Huawei MatePad Pro, primeras impresiones: una clara apuesta por el software propio y adaptado al formato tablet\">\n    </p>\n    <p>Ayer hubo cierto <a href=\"https://www.xataka.com/tag/mwc-2020-virtual\">MWC 2020 virtual</a> y entre las marcas que presentaron novedades estuvo Huawei, con ese nuevo <a href=\"https://www.xataka.com/moviles/huawei-mate-xs-caracteristicas-precio-ficha-tecnica\">Huawei', 11),
(110, 'http://feeds.weblogssl.com/~r/xataka2/~3/SwOCELdR22Q/lenovo-lanza-thinkpad-t-x-l-nueve-portatiles-procesadores-intel-decima-generacion-opcion-amd-ryzen-pro-4000', 'Lenovo lanza los ThinkPad T, X y L: nueve portátiles con procesadores Intel de décima generación y opción de AMD Ryzen PRO 4000', 'Jose García', '15:30:40 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/8aaf02/lenovo/1024_2000.jpg\" alt=\"Lenovo lanza los ThinkPad T, X y L: nueve portátiles con procesadores Intel de décima generación y opción de AMD Ryzen PRO 4000\">\n    </p>\n    <p>Los <strong>Lenovo Thinkpad T, X y L son oficiales</strong>. La compañía acaba de anunciar las novedades que llegarán a su gama de portátiles en este 2020, entre las que destacan una interesante actualización del procesador. Y es que la familia completa suma nueve portátiles en to', 11),
(111, 'http://feeds.weblogssl.com/~r/xataka2/~3/Zl8bKcqMMZA/honor-9x-pro-opiniones-toma-contacto-fotos', 'Honor 9X Pro, primeras impresiones: la difícil tarea de recomendar un (prometedor) gama media sin los servicios de Google', 'Enrique Pérez', '14:00:41 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/985e14/honor-9x-pro-impresiones-ficha/1024_2000.jpg\" alt=\"Honor 9X Pro, primeras impresiones: la difícil tarea de recomendar un (prometedor) gama media sin los servicios de Google\">\n    </p>\n    <p>Honor ofrece móviles excelentes por su precio, pero <strong>este año tienen un desafío extra</strong>. Del mismo modo que Huawei, el fabricante chino se ha visto envuelto en el bloqueo de los EE.UU y deberá vender sus nuevos móviles sin los servicios de Google. E', 11),
(112, 'http://feeds.weblogssl.com/~r/xataka2/~3/dPvpXRBM-YM/horario-partido-cuando-te-comes-perrito-publicidad-que-ves-tecnologia-elige-que-ocurre-estadio-futbol', 'El horario del partido, cuándo te comes el perrito y la publicidad que ves: la tecnología ya elige qué ocurre en el estadio de fútbol', 'Pablo Rodríguez', '13:00:41 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/edb47d/vigkymbeel_17_01_2018_atletico_sevilla_interior_wanda_metropolitano_noche_thunderstruck_2/1024_2000.jpg\" alt=\"El horario del partido, cuándo te comes el perrito y la publicidad que ves: la tecnología ya elige qué ocurre en el estadio de fútbol\">\n    </p>\n    <p>La primera parte ha sido algo floja. Algunas internadas por la banda, un par de tiros a puerta y una sola ocasión clara de gol. El reloj ha superado ampliamente los cuarenta minutos de juego, ', 11),
(113, 'http://feeds.weblogssl.com/~r/xataka2/~3/f-IJdmvS13Q/como-tratamiento-persona-que-da-positivo-coronavirus', 'Cómo es el tratamiento de una persona que da positivo por coronavirus', 'Javier Jiménez', '12:01:42 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/875c00/olga-kononenko-98__mskausi-unsplash/1024_2000.jpg\" alt=\"Cómo es el tratamiento de una persona que da positivo por coronavirus\">\n    </p>\n    <p>La historia del coronavirus lo tenía todo para llenar los titulares de la prensa internacional: un patógeno raro y desconocido, un brote en un país sospechoso y poco transparente y <strong>una carrera contrarreloj por confinar el virus dentro de los límites de la zona que lo vio nacer</strong>. Una carrera qu', 11),
(114, 'http://feeds.weblogssl.com/~r/xataka2/~3/phEE4eAPlnQ/1000-personas-aisladas-tenerife-primer-aislamiento-masivo-espana-tambien-nuestra-primera-gran-prueba-virus', 'Casi mil personas aisladas en Tenerife: el primer aislamiento masivo en España es también nuestra primera gran prueba contra el virus', 'Javier Jiménez', '11:57:21 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/cae403/hotel-h10-costa-adeje-palace-1/1024_2000.jpg\" alt=\"Casi mil personas aisladas en Tenerife: el primer aislamiento masivo en España es también nuestra primera gran prueba contra el virus\">\n    </p>\n    <p><strong>Casi un millar de turistas han sido aislados en un hotel del sur de Tenerife</strong> <a href=\"https://diariodeavisos.elespanol.com/2020/02/el-positivo-por-coronavirus-pone-en-cuarentena-a-unas-1-000-personas-en-el-hotel-h10-costa-adeje-palace', 11),
(115, 'http://feeds.weblogssl.com/~r/xataka2/~3/sb3aIsMkwjI/epidemiologo-harvard-que-predice-que-este-ano-40-70-poblacion-mundial-se-infectaran-coronavirus', 'El epidemiólogo de Harvard que predice que este año entre el 40 y el 70% de la población mundial se infectará con el coronavirus', 'Javier Jiménez', '11:01:42 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/c05516/352434828_1280x720/1024_2000.jpg\" alt=\"El epidemiólogo de Harvard que predice que este año entre el 40 y el 70% de la población mundial se infectará con el coronavirus\">\n    </p>\n    <p>El epidemiólogo en cuestión se llama <a href=\"https://www.hsph.harvard.edu/marc-lipsitch/\">Marc Lipsitch</a> y, efectivamente, <a href=\"https://www.theatlantic.com/health/archive/2020/02/covid-vaccine/607000/\">está convencido</a> de que, en tan solo un año, <strong>en', 11),
(116, 'http://feeds.weblogssl.com/~r/xataka2/~3/laPJDctQzlQ/el-dificil-arte-de-devolver-el-color-a-las-fotografias-antiguas-en-blanco-y-negro', 'El difícil arte de devolver el color a las fotografías antiguas en blanco y negro', 'Juan Carlos López', '10:03:02 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/e4032e/generalpattonap/1024_2000.jpg\" alt=\"El difícil arte de devolver el color a las fotografías antiguas en blanco y negro\">\n    </p>\n    <p>El blanco y negro sigue siendo un recurso muy utilizado por los profesionales de la fotografía. Basta echar un vistazo a algunas de las instantáneas de <a href=\"https://www.xatakafoto.com/fichas/dispositivo-movil/sebastiao-salgado\">Sebastião Salgado</a>, <a href=\"https://www.xatakafoto.com/libros-de-fotografia/minute', 11),
(117, 'http://feeds.weblogssl.com/~r/xataka2/~3/-aMLTcDa7jI/nuevo-citroen-ds-9-llega-tres-versiones-hibridas-enchufables-alcanza-360-cv-potente', 'El nuevo Citroën DS 9 llega con tres versiones híbridas enchufables y alcanza los 360 CV en la más potente', 'Jose García', '09:24:14 2020-02-25', '<p>\n      <img src=\"https://i.blogs.es/215053/ds-9-5-/1024_2000.jpg\" alt=\"El nuevo Citroën DS 9 llega con tres versiones híbridas enchufables y alcanza los 360 CV en la más potente\">\n    </p>\n    <p>DS, la marca con raíces en Citroën y que actúa de forma independiente desde hace ya algún tiempo, acaba de dar a conocer el <strong>nuevo DS 9</strong>. Se trata, por lo tanto, de la primera berlina premium de la marca que llega para sumarse a los dos SUV que actualmente componen su catálogo, véase e', 11),
(118, 'https://www.nytimes.com/2020/02/25/us/politics/south-carolina-debate-recap.html', 'Sanders and Bloomberg Under Attack in Sharp Exchanges in Debate', 'Jonathan Martin and Alexander Burns', '04:22:29 2020-02-26', 'In a messy South Carolina Democratic forum, featuring frequent interruptions, angry crosstalk and theatrical hand-waving, Bernie Sanders faced the most serious test so far.', 12),
(119, 'https://www.nytimes.com/2020/02/25/world/asia/new-delhi-hindu-muslim-violence.html', 'New Delhi Streets Turn Into Battleground, Hindus vs. Muslims', 'Jeffrey Gettleman, Suhasini Raj and Sameer Yasir', '04:21:11 2020-02-26', 'As President Trump toured India’s capital, at least 11 people were killed in mob violence that upended a working-class neighborhood.', 12);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pagina`
--

CREATE TABLE `pagina` (
  `id` int(50) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `subtitulo` varchar(100) NOT NULL,
  `url` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `pagina`
--

INSERT INTO `pagina` (`id`, `nombre`, `subtitulo`, `url`) VALUES
(10, 'Gizmodo en Español', 'Las ultimas noticias en tecnología, ciencia y cultura digital.', 'https://es.gizmodo.com'),
(11, 'Xataka', 'Publicación de noticias sobre gadgets y tecnología. Últimas tecnologías en electrónica de consumo y ', 'http://feeds.weblogssl.com/xataka2.xml'),
(12, 'NYT &gt; Top Stories', '', 'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `articulo`
--
ALTER TABLE `articulo`
  ADD PRIMARY KEY (`id`),
  ADD KEY `pagina` (`id_pagina`);
ALTER TABLE `articulo` ADD FULLTEXT KEY `fullqr` (`titulo`,`autor`,`descripcion`);

--
-- Indices de la tabla `pagina`
--
ALTER TABLE `pagina`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `articulo`
--
ALTER TABLE `articulo`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=120;

--
-- AUTO_INCREMENT de la tabla `pagina`
--
ALTER TABLE `pagina`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `articulo`
--
ALTER TABLE `articulo`
  ADD CONSTRAINT `articulo_ibfk_1` FOREIGN KEY (`id_pagina`) REFERENCES `pagina` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
