-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 20-04-2020 a las 06:09:10
-- Versión del servidor: 10.1.36-MariaDB
-- Versión de PHP: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `noticias`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `articulo`
--

CREATE TABLE `articulo` (
  `id` int(100) NOT NULL,
  `link` varchar(200) NOT NULL,
  `titulo` varchar(500) NOT NULL,
  `autor` varchar(200) NOT NULL,
  `fecha` varchar(50) NOT NULL,
  `hora` varchar(50) NOT NULL,
  `descripcion` varchar(500) NOT NULL,
  `id_pagina` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `articulo`
--

INSERT INTO `articulo` (`id`, `link`, `titulo`, `autor`, `fecha`, `hora`, `descripcion`, `id_pagina`) VALUES
(83, 'https://es.gizmodo.com/nintendo-acude-al-rescate-despues-de-que-a-una-abuela-d-1841917900', 'Nintendo acude al rescate después de que a una abuela de 95 años se le rompiera su Game Boy', 'Andrew Liszewski', '2020-02-25', '23:31:00', '<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--76SXLPrr--/c_fit,fl_progressive,q_80,w_636/twmwkzzftgfly1mqkkiy.jpg\"><p>Nintendo es conocida por su excelente servicio al cliente, pero de vez en cuando la compañía también va mas allá del llamado del deber en casos muy especiales. Cuando los técnicos no pudieron arreglar el <a href=\"https://es.gizmodo.com/relajate-con-este-fantastico-video-en-el-que-restauran-1835198178\">Game Boy original</a> de una mujer japonesa de 95 años, la com', 10),
(172, 'http://feeds.weblogssl.com/~r/xataka2/~3/CBm1eqhQSr0/se-filtra-supuesta-google-card-tarjeta-debito-fisica-totalmente-integrada-android-ecosistema-google', 'Se filtra la (supuesta) Google Card: una tarjeta de dÃ©bito fÃ­sica totalmente integrada con Android y el ecosistema Google', 'Cristian Rus', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/f9445e/1c40cc03-90e9-4d93-bdb3-b35bac905b59/1024_2000.jpeg\" alt=\"Se filtra la (supuesta) Google Card: una tarjeta de dÃ©bito fÃ­sica totalmente integrada con Android y el ecosistema Google\">\n    </p>\n    <p>Siguiendo el camino de <a href=\"https://www.xataka.com/servicios/apple-card-plantea-su-gran-alternativa-al-mundo-fintech-pagos-gestion-finanzas-todo-uno\">Apple con su Apple Card</a>, Google parece estar preparando <strong>su propia tarjeta de dÃ©bito fÃ', 11),
(173, 'http://feeds.weblogssl.com/~r/xataka2/~3/pVtfCjSXxtw/huawei-watch-gt-2e-analisis-caracteristicas-precio-ficha-tecnica', 'Huawei Watch GT 2e, anÃ¡lisis: el diseÃ±o mÃ¡s deportivo atrae, la autonomÃ­a enamora', 'Jose GarcÃ­a', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/3d8da6/huawei-watch-gt-2e-4-/1024_2000.jpg\" alt=\"Huawei Watch GT 2e, anÃ¡lisis: el diseÃ±o mÃ¡s deportivo atrae, la autonomÃ­a enamora\">\n    </p>\n    <p>Aprovechando el lanzamiento de los <a href=\"https://www.xataka.com/moviles/huawei-p40-precio-caracteristicas-precio-ficha-tecnica\">Huawei P40</a>, <a href=\"https://www.xataka.com/analisis/huawei-p40-pro-analisis-caracteristicas-precio-especificaciones\">P40 Pro</a> y <a href=\"https://www.xataka.com/moviles/', 11),
(174, 'http://feeds.weblogssl.com/~r/xataka2/~3/lGtn0xG6Lm4/costaba-4-999-euros-tenia-11-pulgadas-asi-era-primer-televisor-oled-pionero-sony-xel-1', 'Costaba 4.999 euros y tenÃ­a 11 pulgadas: asÃ­ era el primer televisor OLED, el pionero Sony XEL-1', 'Enrique PÃ©rez', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/19a01b/sony_oled/1024_2000.jpg\" alt=\"Costaba 4.999 euros y tenÃ­a 11 pulgadas: asÃ­ era el primer televisor OLED, el pionero Sony XEL-1\">\n    </p>\n    <p>Steven Van Slyke desarrollÃ³ la tecnologÃ­a OLED en <a href=\"https://www.invent.org/inductees/steven-van-slyke\">1979</a>, mientras trabajaba en Eastman Kodak. Pero no fue hasta 1997 cuando Pioneer incorporÃ³ un panel de este tipo por primera vez en un dispositivo comercial; una radio para el coche. Hoy en', 11),
(175, 'http://feeds.weblogssl.com/~r/xataka2/~3/acHXGBDvGQU/microsoft-edge-trucos-funciones-para-sacar-partido-navegador-microsoft', 'Microsoft Edge: 31 trucos y funciones para sacar partido del navegador de Microsoft', 'YÃºbal FM', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/b046a7/edge/1024_2000.jpg\" alt=\"Microsoft Edge: 31 trucos y funciones para sacar partido del navegador de Microsoft\">\n    </p>\n    <p>Te traemos un recopilatorio de <strong>31 trucos para que saques el mÃ¡ximo partido del navegador Microsoft Edge</strong>, en <a href=\"https://www.xataka.com/basics/como-descargar-microsoft-edge-conseguir-version-basada-chromium\">su versiÃ³n basada en Chromium</a> que se ha estrenado en este 2020. Edge ya estÃ¡ en segundo lu', 11),
(176, 'http://feeds.weblogssl.com/~r/xataka2/~3/UFH2uLb6uDo/tecnologia-competencia-aparente-que-kindle-apple-watch-tienda-amazon-chrome-campan-a-sus-anchas', 'TecnologÃ­a sin competencia aparente: por quÃ© el Kindle, el Apple Watch, la tienda de Amazon o Chrome campan a sus anchas', 'Javier Pastor', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/fb34a7/monopolio1/1024_2000.jpg\" alt=\"TecnologÃ­a sin competencia aparente: por quÃ© el Kindle, el Apple Watch, la tienda de Amazon o Chrome campan a sus anchas\">\n    </p>\n    <p>Si alguien nos pregunta por un lector de libros electrÃ³nicos, <strong>lo primero que se nos viene a la cabeza es un Kindle</strong>. No un Kobo, un Woxter o un Targus. Lo mismo con los relojes inteligentes: estÃ¡ el Apple Watch y luego alternativas menos populares como los modelo', 11),
(177, 'http://feeds.weblogssl.com/~r/xataka2/~3/mnMu0sQS-H4/sindrome-vivir-miedo-a-convertirte-programador-oxidado', 'El sÃ­ndrome de vivir con miedo a convertirte en un programador oxidado', 'Arantxa Herranz', '2020-04-19', '', '\n<p>\n      <img src=\"https://i.blogs.es/1e5f81/portada-oxido/1024_2000.png\" alt=\"El sÃ­ndrome de vivir con miedo a convertirte en un programador oxidado\">\n    </p>\n    <p>SegÃºn <a href=\"http://www.info.univ-angers.fr/~gh/hilapr/langlist/langlist.htm\">The Language List</a>, <strong>desde 1991 ha habido 2.500 lenguajes de programaciÃ³n</strong>, aunque en la actualidad podrÃ­amos reducirlos a 258 segÃºn el <a href=\"https://www.tiobe.com/tiobe-index/\">TIOBE Index</a> (que se actualiza cada mes). Y', 11),
(178, 'http://feeds.weblogssl.com/~r/xataka2/~3/k3bO2uTaVz0/he-estado-buscando-fps-apto-para-mis-hijos-industria-videojuego-no-me-ha-puesto-facil', 'He estado buscando un FPS apto para mis hijos, pero la industria del videojuego no me lo ha puesto fÃ¡cil', 'R. MÃ¡rquez', '2020-04-18', '', '\n<p>\n      <img src=\"https://i.blogs.es/e5c09b/overwatchkids/1024_2000.jpg\" alt=\"He estado buscando un FPS apto para mis hijos, pero la industria del videojuego no me lo ha puesto fÃ¡cil\">\n    </p>\n    <p>Pongamos que eres una madre, padre, tÃ­o o relativo a un <strong>niÃ±o de diez aÃ±os</strong>. Digamos que conoces el mundo del videojuego pero has estado aislado de Ã©l durante un tiempo porque no se puede seguir la actualidad de todo, y ahora planeas volver con la intenciÃ³n de jugar con el c', 11),
(179, 'http://feeds.weblogssl.com/~r/xataka2/~3/v0NoKTcdtLw/he-intentado-usar-deepfakes-para-transformarme-elon-musk-eminem-mis-videollamadas-sale-mal', 'He intentado usar deepfakes para transformarme en Elon Musk y Eminem en mis videollamadas: sale mal', 'Jose GarcÃ­a', '2020-04-18', '', '\n<p>\n      <img src=\"https://i.blogs.es/8823c0/musk/1024_2000.jpg\" alt=\"He intentado usar deepfakes para transformarme en Elon Musk y Eminem en mis videollamadas: sale mal\">\n    </p>\n    <p>Seguramente hayas oÃ­do hablar alguna vez de los <strong>deepfakes</strong>, una tecnologÃ­a que usa redes neuronales para manipular vÃ­deos y audios. Se han usado para manipular clips de polÃ­ticos (como <a href=\"https://www.youtube.com/watch?v=cQ54GDm1eL0&amp;feature=youtu.be\">Obama</a>) o grandes empresari', 11),
(180, 'http://feeds.weblogssl.com/~r/xataka2/~3/VJWEeW-sAbc/cuadernos-a-teams-dia-para-otro-asi-viven-confinamiento-tres-profesoras-distintos-perfiles-tecnologicos', 'De los cuadernos a Teams de un dÃ­a para otro: asÃ­ viven el confinamiento tres profesoras con distintos perfiles tecnolÃ³gicos', 'Javier Lacort', '2020-04-18', '', '\n<p>\n      <img src=\"https://i.blogs.es/426fc0/3-profesoras/1024_2000.jpg\" alt=\"De los cuadernos a Teams de un dÃ­a para otro: asÃ­ viven el confinamiento tres profesoras con distintos perfiles tecnolÃ³gicos\">\n    </p>\n    <p>El <a href=\"https://www.xataka.com/legislacion-y-derechos/gobierno-declara-cuarentena-obligatoria-toda-espana-excepciones-esto-que-se-podra-hacer\">confinamiento</a> repentino tuvo muchas consecuencias, y una de ellas fue <strong>ver cÃ³mo las clases se vaciaban de un dÃ­a p', 11),
(182, 'https://www.nytimes.com/news-event/coronavirus', 'Full Coronavirus Coverage', 'The New York Times', '2020-04-20', '', '', 12),
(183, 'https://www.nytimes.com/2020/04/19/world/canada/nova-scotia-shooting-gabriel-wortman.html', 'At Least 16 Killed in Nova Scotia Shooting, Police Say', 'Dan Bilefsky and Johnny Diaz', '2020-04-20', '', 'One Royal Canadian Mounted Police officer was killed and another was wounded, officials said.', 12),
(184, 'https://www.nytimes.com/2020/04/19/nyregion/coronavirus-nj-andover-nursing-home-deaths.html', '70 Died at a Nursing Home As Body Bags Piled Up. This Is What Went Wrong.', 'Tracey Tully, Brian M. Rosenthal, Matthew Goldstein and Robert Gebeloff', '2020-04-20', '', 'The sprawling New Jersey nursing home, which was chronically short of staff and protective equipment, quickly fell prey to the coronavirus.', 12),
(185, 'https://www.nytimes.com/2020/04/19/us/coronavirus-updates.html', 'Coronavirus Live Updates: Trump, Facing Criticism, Says He Will Increase Swab Production', 'Unknown', '2020-04-20', '', 'Governors say reopening their economies must be linked with wider testing for the virus but they continue to face shortages of supplies and testing kits.', 12),
(186, 'https://www.nytimes.com/2020/04/19/nyregion/coronavirus-new-york-update.html', 'De Blasio Pleads With Trump for Funding to Alleviate Virus Damage', 'Unknown', '2020-04-20', '', 'Mayor Bill de Blasio compared President Trump to Gerald Ford and asked if he was telling New York City to â€˜drop dead.â€™', 12),
(187, 'https://www.nytimes.com/2020/04/19/world/coronavirus-news.html', 'Chile, India, France: Coronavirus World News Updates', 'Unknown', '2020-04-20', '', 'The pandemic has reached Afghanistanâ€™s presidential palace. Volunteers are stoking divisions as they tighten Indiaâ€™s lockdown.', 12),
(188, 'https://www.nytimes.com/2020/04/19/opinion/trump-coronavirus-briefings.html', 'Stop Airing Trumpâ€™s Briefings!', 'Charles M. Blow', '2020-04-20', '', 'The media is allowing disinformation to appear as news.', 12),
(189, 'https://www.nytimes.com/2020/04/19/us/politics/coronavirus-small-business-aid-congress.html', 'White House and Democrats Near Deal on Aid for Small Businesses', 'Sheryl Gay Stolberg and Alan Rappeport', '2020-04-20', '', 'The $450 billion agreement would also include more money for hospitals and coronavirus testing, which Democrats had insisted on.', 12),
(190, 'https://www.nytimes.com/2020/04/19/us/dallas-dart-bus-police-shooting.html', 'Texas Bus Hijacking Leaves 2 Officers Wounded and Gunman Dead', 'Mariel Padilla', '2020-04-20', '', 'The gunman, identified by authorities as Ramon Thomas Villagomez, was a suspect in a San Antonio murder.', 12),
(191, 'https://www.nytimes.com/2020/04/19/us/coronavirus-antibody-tests.html', 'Covid-19 Antibody Test, Seen as Key to Reopening Country, Does Not Yet Deliver', 'Steve Eder, Megan Twohey and Apoorva Mandavilli', '2020-04-20', '', 'The tests, many made in China without F.D.A. approval, are often inaccurate. Some doctors are misusing them. The rollout is nowhere close to the demand.', 12),
(192, 'https://www.nytimes.com/2020/04/19/world/europe/russia-komi-coronavirus.html', 'In Pandemic, a Remote Russian Region Orders a Lockdown â€” on Information', 'Andrew Higgins', '2020-04-20', '', 'Trailing only Moscow in per capita infection, Komi faces a serious health crisis and wants to know who leaked the bad news.', 12),
(193, 'https://www.nytimes.com/2020/04/19/arts/peter-beard-dead.html', 'Peter Beard, Wildlife Photographer on the Wild Side, Dies at 82', 'Margalit Fox', '2020-04-20', '', 'Called â€œthe last of the adventurers,â€ Mr. Beard photographed African fauna at great personal risk, and well into old age could party till dawn. He had been missing for 19 days.', 12),
(194, 'https://www.nytimes.com/2020/04/18/nyregion/coronavirus-jjbubbles-joe-joyce.html', 'A Beloved Bar Owner Was Skeptical About the Virus. Then He Took a Cruise.', 'Ginia Bellafante', '2020-04-19', '', 'Joe Joyce oversaw JJ Bubbles, a welcoming tavern in a conservative corner of Brooklyn, for 43 years until he died of Covid-19.', 12),
(195, 'https://www.nytimes.com/2020/04/19/opinion/coronavirus-trump-protests.html', 'Protesting for the Right to Catch the Coronavirus', 'Charlie Warzel', '2020-04-19', '', 'The reopen America protests are the logical conclusion of a twisted liberty movement.', 12),
(196, 'https://www.nytimes.com/2020/04/19/opinion/coronavirus-inequality-bernie-sanders.html', 'Bernie Sanders: The Foundations of American Society Are Failing Us', 'Bernie Sanders', '2020-04-19', '', 'The unequal impact of the pandemic and economic collapse are forcing us to rethink the assumptions of our system.', 12),
(197, 'https://www.nytimes.com/2020/04/19/opinion/trump-impeachment-coronavirus.html', 'Impeachment Taught Trump All the Wrong Lessons', 'Barry Berke', '2020-04-19', '', 'He thinks he can get away with anything.', 12),
(198, 'https://www.nytimes.com/2020/04/19/opinion/coronavirus-newspapers-journalism.html', 'Google and Facebook Must Pay for Local Journalism', 'David Chavern', '2020-04-19', '', 'The U.S. should emulate the French governmentâ€™s resolve to fight for the news media industry.', 12),
(199, 'https://www.nytimes.com/2020/04/19/us/politics/charlie-kirk-conservatives-coronavirus.html', 'For Charlie Kirk, Conservative Activist, the Coronavirus Is a Cudgel', 'Matthew Rosenberg and Katie Rogers', '2020-04-19', '', 'Mixing, matching and twisting facts about the coronavirus online, Mr. Kirk has created a template for a new kind of political agitator.', 12),
(200, 'https://www.nytimes.com/2020/04/19/movies/nobuhiko-obayashi-dead.html', 'Nobuhiko Obayashi, Unpredictable Japanese Director, Dies at 82', 'Neil Genzlinger', '2020-04-19', '', 'He made a splash in 1977 with a horror movie about a  house full of furniture that eats schoolgirls. His later movies explored a range of themes.', 12),
(201, 'https://www.nytimes.com/2020/04/19/us/coronavirus-bars-cash-donations.html', 'Bars and Restaurants Peel Cash From Walls to Help Idled Workers', 'Johnny Diaz', '2020-04-19', '', 'Owners are removing currency that had been stapled or taped inside their businesses to donate to employees affected by the coronavirus shutdown.', 12),
(202, 'https://www.nytimes.com/2020/04/19/nyregion/new-york-new-jersey-coronavirus-hospitals.html', 'He Went to 3 Hospitals. When He Finally Got a Bed, It Was Too Late.', 'Andrea Salcedo', '2020-04-19', '', 'Luis Arellanoâ€™s struggle to receive care illustrates the difficult decisions hospitals have to make in caring for coronavirus patients. They can mean the difference between life and death.', 12),
(203, 'https://www.nytimes.com/2020/04/19/world/asia/samsung-tower-protest.html', 'â€˜My Last Standâ€™: In South Korea, a Protesterâ€™s Lone Fight Against Samsung', 'Choe Sang-Hun', '2020-04-19', '', 'Kim Yong-hee has been â€‹staging sit-ins and hunger strikes at the top of an 82-foot-tall traffic camera tower overlooking the busiest intersection in Seoul â€” for more than 300 days and counting.', 12),
(204, 'https://www.nytimes.com/2020/04/19/climate/deepwater-horizon-anniversary.html', 'Deepwater Horizon Ten Years On', 'Lisa Friedman', '2020-04-19', '', 'Members of the bipartisan commission created to investigate the spill say Congress and the Trump administration have failed to take safety seriously.', 12),
(205, 'https://www.nytimes.com/2020/04/19/world/asia/tokyo-japan-coronavirus.html', 'Tokyo, in a State of Emergency, Yet Still Having Drinks at a Bar', 'Motoko Rich', '2020-04-19', '', 'Tokyo may have been lulled into complacency during the weeks when Japan contained the coronavirus while avoiding economically devastating lockdowns, our bureau chief writes.', 12),
(206, 'https://www.nytimes.com/2020/04/19/world/asia/north-korea-denies-nice-note-trump.html', 'North Korea Denies Sending a â€˜Nice Noteâ€™ to Trump', 'Choe Sang-Hun', '2020-04-19', '', 'â€‹The Northâ€™s Foreign Ministry â€‹disputed an assertion by President Trump and warned that his relationship with Kim Jong-un should not â€œbe misused for meeting selfish purposes.â€', 12),
(207, 'https://www.nytimes.com/2020/04/18/arts/william-bailey-dead.html', 'William Bailey, Modernist Figurative Painter, Dies at 89', 'William Grimes', '2020-04-19', '', 'He swathed his nudes and still lifes of eggs, vases, bottles and bowls in a breathless, deceptively serene atmosphere heavy with mystery.', 12),
(208, 'https://www.nytimes.com/2020/04/19/opinion/gavin-newsom-california-coronavirus.html', 'Can Gavin Newsom Lead California Through the Coronavirus Pandemic?', 'Miriam Pawel', '2020-04-19', '', 'The governor has delivered fanfare. Now he must lead the state through the calamities of the pandemic.', 12),
(209, 'https://www.nytimes.com/2020/04/19/opinion/deepwater-horizon.html', 'A Decade After Deepwater Horizon', 'The Editorial Board', '2020-04-19', '', 'Rolling back regulations ignores the central lessons from the countryâ€™s largest oil spill.', 12),
(210, 'https://www.nytimes.com/newsletters/watching', 'Sign Up: â€˜Watchingâ€™', 'The New York Times', '2020-04-19', '', 'Get recommendations on the best TV shows and movies to watch.', 12),
(211, 'https://www.nytimes.com/newsletters/coronavirus-briefing', 'Sign Up: â€˜Coronavirus Briefingâ€™', 'The New York Times', '2020-04-19', '', 'An informed guide to the global outbreak.', 12),
(212, 'https://www.nytimes.com/2020/04/19/podcasts/the-daily/the-woman-who-might-find-us-another-earth.html', 'The Sunday Read: The Woman Who Might Find Us Another Earth', 'Unknown', '2020-04-19', '', 'The star-crossed life of Sara Seager, an astrophysicist obsessed with discovering the possibility of other life in the universe.', 12),
(213, 'https://www.nytimes.com/2020/04/19/nyregion/coronavirus-nyc-islands-protection.html', 'â€˜Turn Around, Go Backâ€™: Summer Islands Donâ€™t Want Coronavirus, or You', 'Corey Kilgannon', '2020-04-19', '', 'With few medical resources to fight the virus, residents of the island havens east of New York City have fiercely protected their secluded hometowns.', 12),
(214, 'https://www.nytimes.com/2020/04/18/nyregion/ming-tiger-harlem-nyc.html', 'A 425-Pound Tiger Living in a Harlem Apartment? Yes, It Happened', 'Corey Kilgannon', '2020-04-19', '', 'Before â€œTiger King,â€ there was New Yorkâ€™s infamous Tiger Man.', 12),
(215, 'https://www.nytimes.com/2020/04/19/world/americas/bolsonaro-brazil-amazon-indigenous.html', 'As Bolsonaro Keeps Amazon Vows, Brazilâ€™s Indigenous Fear â€˜Ethnocideâ€™', 'Ernesto LondoÃ±o and LetÃ­cia Casado', '2020-04-19', '', 'President Jair Bolsonaro is moving aggressively to open up the Amazon rainforest to commercial development, posing an existential threat to the tribes living there.', 12),
(216, 'https://www.nytimes.com/2020/04/18/opinion/coronavirus-documentaries-streaming.html', 'Need More Than Netflix? These 15 Short Films Are Worth Your Time', 'Unknown', '2020-04-18', '', 'Here are some crowd-pleasing documentaries for short attention spans â€” and tight budgets. You can stream them right here.', 12),
(217, 'https://www.nytimes.com/2020/04/18/opinion/covid-cooking-health.html', 'How Covid-19 Is Making Millions of Americans Healthier', 'Hans Taparia', '2020-04-18', '', 'People are finally cooking more.', 12),
(218, 'https://www.nytimes.com/2020/04/17/well/live/coronavirus-contagion-spead-clothes-shoes-hair-newspaper-packages-mail-infectious.html', 'Is the Virus on My Clothes? My Shoes? My Hair? My Newspaper?', 'Tara Parker-Pope', '2020-04-18', '', 'We asked the experts to answer questions about all the places coronavirus lurks (or doesnâ€™t). Youâ€™ll feel better after reading this.', 12),
(219, 'https://www.nytimes.com/2020/04/18/us/coronavirus-deficits-spending.html', 'No Fight Over Red Ink Now, but Virus Spending Will Force Tough Choices', 'Carl Hulse', '2020-04-18', '', 'The surge of deficit spending to â€œnever-before-seen levelsâ€ is viewed as necessary, but dangerous for the future.', 12),
(220, 'https://www.nytimes.com/2020/04/17/movies/derek-jarman-garden-prospect-cottage.html', 'Planted in Sickness, Derek Jarmanâ€™s Garden Still Gives Joy', 'Mary Katharine Tramontana', '2020-04-18', '', 'The British filmmaker, who died of an AIDS-related illness in 1994, found solace in gardening during a public health crisis.', 12),
(239, 'https://es.gizmodo.com/asi-es-el-iphone-12-segun-la-misma-persona-que-filtro-1842927044', 'AsÃ­ es el iPhone 12, segÃºn la misma persona que filtrÃ³ el Galaxy S20', 'MatÃ­as S. Zavia', '2020-04-18', '00:48:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--avOZ3MUN--/c_fit,fl_progressive,q_80,w_636/uirbyxpgktrmwkkfi2mg.jpg\"><p>Quedan unos meses para que se presente el sucesor del iPhone 11, pero Max Weinbach â€”conocido por <a href=\"https://es.gizmodo.com/las-primeras-fotos-del-samsung-galaxy-s20-muestran-una-1840975119\">haber filtrado</a>Â <a href=\"https://es.gizmodo.com/espero-que-este-rumor-sobre-el-telefono-plegable-de-sam-1841208545\">los Ãºltimos telÃ©fonos</a> <a href=\"https://e', 10),
(240, 'https://es.gizmodo.com/como-instalar-la-nueva-actualizacion-mayor-de-windows-1-1842926885', 'CÃ³mo instalar la nueva actualizaciÃ³n mayor de Windows 10 ahora mismo (y quÃ© incluye)', 'Brendan Hesse', '2020-04-18', '00:21:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--_0daibWd--/c_fit,fl_progressive,q_80,w_636/carcudhmttwmojtqqism.jpg\"><p><a href=\"https://es.gizmodo.com/asi-trabaja-el-equipo-rojo-de-microsoft-el-grupo-de-ha-1829443428\">Microsoft</a> lanza dos grandes actualizaciones de <a href=\"https://es.gizmodo.com/actualiza-windows-10-ahora-mismo-para-corregir-dos-vuln-1842889026\">Windows 10</a> cada aÃ±o, y la primera de 2020, llamada Windows 10 VersiÃ³n 2004, llegarÃ¡ en apenas un par de sem', 10),
(241, 'https://es.gizmodo.com/whatsapp-permitira-hacer-videollamadas-grupales-de-mas-1842925607', 'WhatsApp permitirÃ¡ hacer videollamadas grupales de mÃ¡s de cuatro personas', 'Eduardo MarÃ­n', '2020-04-17', '22:39:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--xwXbglGX--/c_fit,fl_progressive,q_80,w_636/orycngirizhtbygcgmza.jpg\"><p>Grandes noticias para los mÃ¡s de <a href=\"https://blog.whatsapp.com/10000666/Two-Billion-Users%E2%80%94Connecting-the-World-Privately\" target=\"_blank\" rel=\"noopener noreferrer\">2.000 millones</a> de usuarios de <a href=\"https://es.gizmodo.com/asi-funcionan-los-mensajes-que-se-autodestruyen-en-what-1842404764\">WhatsApp</a> (sÃ­, tiene tantos usuarios). La plataf', 10),
(242, 'https://es.gizmodo.com/la-nasa-pone-fecha-al-primer-lanzamiento-tripulado-de-s-1842924546', 'La NASA pone fecha al primer lanzamiento tripulado de SpaceX: 27 de mayo', 'MatÃ­as S. Zavia', '2020-04-17', '21:30:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--vyBB_05k--/c_fit,fl_progressive,q_80,w_636/ttwmianduu03ciav4lmo.jpg\"><p>Todo listo para que Estados Unidos vuelva a lanzar astronautas desde Cabo CaÃ±averal, algo que no ocurrÃ­a desde que el transbordador espacial fue retirado en 2011.<br></p>\n<p><a href=\"https://es.gizmodo.com/la-nasa-pone-fecha-al-primer-lanzamiento-tripulado-de-s-1842924546\">Read more...</a></p>\n', 10),
(243, 'https://es.gizmodo.com/estos-son-los-mas-de-60-cursos-de-harvard-que-puedes-ha-1842923386', 'Estos son los mÃ¡s de 60 cursos de Harvard que puedes hacer gratis desde casa en cuarentena', 'Eduardo MarÃ­n', '2020-04-17', '20:15:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--lUpjeVLb--/c_fit,fl_progressive,q_80,w_636/s9vss4kwvmy65uhiaqzh.jpg\"><p>Vivimos en medio de una pandemia. La mayorÃ­a de gobiernos del mundo recomiendan quedarse en casa en <a href=\"https://es.gizmodo.com/mira-cuanto-ha-bajado-el-trafico-de-tu-ciudad-durante-e-1842890789\">cuarentena</a> en la medida de lo posible, pero eso no significa que no podamos aprovechar ese tiempo para aprender cosas nuevas. Afortunadamente, Harvard estÃ¡ re', 10),
(244, 'https://es.gizmodo.com/samsung-redisena-las-cajas-de-sus-televisores-para-que-1842921611', 'Samsung rediseÃ±a las cajas de sus televisores para que se conviertan en casas para gatos', 'Andrew Liszewski', '2020-04-17', '18:35:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--h-oAoG2M--/c_fit,fl_progressive,q_80,w_636/caffieybykcsr3tpgfyf.jpg\"><p>Siguiendo el ejemplo de los niÃ±os de 10 aÃ±os que encuentran infinitos usos creativos para una caja de cartÃ³n vacÃ­a, Samsung <a href=\"https://news.samsung.com/global/samsung-to-introduce-eco-packaging-for-its-lifestyle-tv-lineup\" target=\"_blank\" rel=\"noopener noreferrer\">ha decidido facilitar a sus clientes</a> el reciclaje de las cajas de sus televisores con', 10),
(245, 'https://es.gizmodo.com/estas-gafas-inteligentes-se-usan-para-detectar-sintomas-1842921832', 'Estas gafas inteligentes se usan para detectar sÃ­ntomas del coronavirus', 'Eduardo MarÃ­n', '2020-04-17', '18:18:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--jscxLXPe--/c_fit,fl_progressive,q_80,w_636/uzjixlrvmfpkyujajxnd.png\"><p>Una de las formas de detectar posibles contagios de <a href=\"https://es.gizmodo.com/un-medico-comparte-las-tecnicas-de-respiracion-para-aqu-1842719870\">coronavirus</a> es mediante un chequeo de temperatura corporal, dado que la fiebre, ademÃ¡s de la tos constante, son dos de los sÃ­ntomas comunes del covidâ€“19. Una startup china ha diseÃ±ado unas gafas wearable', 10),
(246, 'https://es.gizmodo.com/el-nuevo-ipad-pro-esta-cerca-de-convertirse-en-el-porta-1842920602', 'El nuevo iPad Pro estÃ¡ cerca de convertirse en el portÃ¡til que quiero', 'Caitlin McGarry', '2020-04-17', '17:42:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--uXEMNQ0Y--/c_fit,fl_progressive,q_80,w_636/hfqtvrd1qhmjovznxh1u.jpg\"><p>Soy un bicho raro.</p>\n<p><a href=\"https://es.gizmodo.com/el-nuevo-ipad-pro-esta-cerca-de-convertirse-en-el-porta-1842920602\">Read more...</a></p>\n', 10),
(247, 'https://es.gizmodo.com/el-trailer-de-z-eleva-la-tipica-trama-del-amigo-imagi-1842917953', 'El trÃ¡iler de \"Z\" eleva la tÃ­pica trama del amigo imaginario a niveles terrorÃ­ficos', 'Cheryl Eddy', '2020-04-17', '14:46:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--mF71391g--/c_fit,fl_progressive,q_80,w_636/g1sjogez94s37cahth54.jpg\"><p>En el cine de terror nunca es bueno que el niÃ±o tenga un compaÃ±ero de juegos imaginario: piensa en Jodie, el cerdo demoniaco de <em>Amityville Horror</em>; en <a href=\"https://es.gizmodo.com/las-20-peliculas-de-terror-mas-espeluznantes-de-la-ulti-1779167493\">TomÃ¡s, el fantasma</a> de <em>El Orfanato</em>; o Abigail, el no-fantasma de <a href=\"https://es.gizmo', 10),
(248, 'https://es.gizmodo.com/destiny-2-tendra-su-propia-version-de-los-juegos-olimpi-1842916888', 'Destiny 2 tendrÃ¡ su propia versiÃ³n de los Juegos OlÃ­mpicos', 'Ethan Gach', '2020-04-17', '12:56:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--ZMBq3khx--/c_fit,fl_progressive,q_80,w_636/u8vowwzu4ikbgwyqnnhc.png\"><p><em>Destiny 2</em> tendrÃ¡ un nuevo evento por tiempo limitado llamado <em>Juegos de guardianes</em> durante prÃ³xima semana. Este evento harÃ¡ que los jugadores intenten competir entre sÃ­ por el honor de tener a su clase de guardiÃ¡n representada en la Torre durante el resto del aÃ±o.</p>\n<p><a href=\"https://es.gizmodo.com/destiny-2-tendra-su-propia-version-de', 10),
(249, 'https://es.gizmodo.com/alguien-llevo-una-maleta-llena-de-cangrejos-vivos-en-av-1842916655', 'Alguien llevÃ³ una maleta llena de cangrejos vivos en aviÃ³n. Y la maleta se abriÃ³', 'Miguel Jorge', '2020-04-17', '12:15:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--7-BbK2IY--/c_fit,fl_progressive,q_80,w_636/tnl9pso0kjzhfg93psbw.jpg\"><p>Â <br></p>\n<p><a href=\"https://es.gizmodo.com/alguien-llevo-una-maleta-llena-de-cangrejos-vivos-en-av-1842916655\">Read more...</a></p>\n', 10),
(250, 'https://es.gizmodo.com/como-convertirte-en-elon-musk-o-cualquier-famoso-dura-1842916285', 'CÃ³mo convertirte en Elon Musk (o cualquier famoso) durante una videollamada de Zoom o Skype', 'Miguel Jorge', '2020-04-17', '11:08:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--NqbaHEaN--/c_fit,fl_progressive,q_80,w_636/aejo3li6wnzq1pymsfpa.gif\"><p>Zoom, Skype y similares son la soluciÃ³n que ha encontrado parte del planeta para sobrellevar la cuarentena sin perder el contacto â€œsocialâ€ con su cÃ­rculo cercano. Por eso no es de extraÃ±ar que surjan aplicaciones y programas en torno a ellos como <a href=\"https://github.com/alievk/avatarify\" target=\"_blank\" rel=\"noopener noreferrer\">Avatarify</a>: deepfak', 10),
(251, 'https://es.gizmodo.com/cuidado-con-los-correos-sobre-covid-19-google-registra-1842916269', 'Cuidado con los correos sobre covid-19: Google registra 18 millones de mensajes con malware sobre la pandemia al dÃ­a', 'Carlos Zahumenszky', '2020-04-17', '11:04:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--U-1ed-IQ--/c_fit,fl_progressive,q_80,w_636/q1pfudortwkbffqmwvsc.gif\"><p>Cada dÃ­a de la semana pasada circularon mÃ¡s de 18 millones de correos electrÃ³nicos con malware o estafas tipo phising dedicados a la pandemia de covid-19. Eso por no mencionar los 240 millones de correos basura sobre la pandemia.<br></p>\n<p><a href=\"https://es.gizmodo.com/cuidado-con-los-correos-sobre-covid-19-google-registra-1842916269\">Read more...</a></p>\n', 10),
(252, 'https://es.gizmodo.com/se-filtran-nuevos-detalles-de-la-surface-book-3-de-micr-1842915981', 'Se filtran nuevos detalles de la Surface Book 3 de Microsoft', 'Sam Rutherford', '2020-04-17', '10:23:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--zxxG9vof--/c_fit,fl_progressive,q_80,w_636/r2wurhr7fykvwkz8giks.jpg\"><p><a href=\"https://gizmodo.com/microsofts-surface-go-2-shows-up-in-fcc-filings-1842859923\">Hace solo un par de dÃ­as</a>, aparecieron noticias sobre una posible Surface Go 2 en Internet. Pero ahora, parece que tenemos informaciÃ³n sobre un portÃ¡til diferente de Microsoft, gracias a una lista de productos filtrada en Europa.</p>\n<p><a href=\"https://es.gizmodo.com/', 10),
(253, 'https://es.gizmodo.com/pronto-seremos-buenos-amigos-el-momento-en-que-un-pe-1842915654', 'â€œPronto seremos buenos amigosâ€: el momento en que un perro maltratado se rinde a las caricias por primera vez', 'Miguel Jorge', '2020-04-17', '09:49:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--8p9dmRl4--/c_fit,fl_progressive,q_80,w_636/ni2xzvcdty1qp9aarqdd.gif\"><p>En apenas un minuto <a href=\"https://www.youtube.com/watch?v=LddAEl0vMRY\" target=\"_blank\" rel=\"noopener noreferrer\">de secuencia</a> vemos una escena desgarradora y hermosa, es el tiempo que pasa una criatura, probablemente torturada una y mil veces, de sentir miedo a algo muy distinto mÃ¡s allÃ¡ de los golpes y la violencia diaria. Es el tiempo que pasa un perr', 10),
(254, 'https://es.gizmodo.com/descubren-el-planeta-potencialmente-habitable-mas-parec-1842915536', 'Descubren el planeta potencialmente habitable mÃ¡s parecido a la Tierra en la lista de descartados de Kepler', 'George Dvorsky', '2020-04-17', '09:30:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--NsZ6GXXP--/c_fit,fl_progressive,q_80,w_636/qj0mbr3vteuszn3zhhex.jpg\"><p>Un equipo de expertos lleva aÃ±os dedicado a revisar la montaÃ±a de datos descartados del telescopio espacial Kepler con la esperanza de encontrar algo que las computadoras hubieran pasado por alto. Ese esfuerzo se ha saldado con el descubrimiento del planeta mÃ¡s parecido a la Tierra hasta ahora.</p>\n<p><a href=\"https://es.gizmodo.com/descubren-el-planeta-poten', 10),
(255, 'https://es.gizmodo.com/selena-gomez-demanda-a-un-juego-por-10-millones-de-dola-1842915289', 'Selena Gomez demanda a un juego por 10 millones de dÃ³lares por robar su imagen', 'Luke Plunkett', '2020-04-17', '09:00:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--lq7ghFIJ--/c_fit,fl_progressive,q_80,w_636/ebwn8iebefpo3xfkdw46.jpg\"><p>Selena Gomez ha presentado una demanda de 10 millones de dÃ³lares contra las compaÃ±Ã­as responsables de <em>Clothes Forever - Styling Game</em>, un juego para telÃ©fonos que, por su propia cuenta, â€œ<em>te permitirÃ¡ vivir todas tus fantasÃ­as y convertirte en la fashionista que naciste para ser</em>â€.<br></p>\n<p><a href=\"https://es.gizmodo.com/selena-gomez-', 10),
(256, 'https://es.gizmodo.com/j-j-abrams-hara-una-serie-de-el-resplandor-y-de-la-lig-1842910145', 'J.J. Abrams harÃ¡ una serie de El Resplandor y de La liga de la justicia oscura', 'Beth Elderkin', '2020-04-17', '00:46:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--I99p4UY8--/c_fit,fl_progressive,q_80,w_636/sb5sf0saca8vdjvh1yhf.png\"><p>Por fin, alguien harÃ¡ <a href=\"https://io9.gizmodo.com/justice-league-dark-proves-that-the-world-still-needs-m-1792004712\"><em>Justice League Dark</em></a>, aunque no de la manera que <a href=\"https://io9.gizmodo.com/joseph-kahns-unused-justice-league-dark-designs-are-fab-1821366868\">esperÃ¡bamos</a>. J.J. Abrams ya ha anunciado sus primeras tres series para el', 10),
(257, 'https://es.gizmodo.com/los-simpson-tambien-se-han-quedado-en-casa-en-cuarenten-1842909715', 'Los Simpson tambiÃ©n se han quedado en casa en cuarentena en su Ãºltimo episodio', 'Eduardo MarÃ­n', '2020-04-16', '23:58:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--SAiQxi3s--/c_fit,fl_progressive,q_80,w_636/nib6opyjjokp5u0zeigz.gif\"><p>Durante mÃ¡s de 30 aÃ±os cada episodio de <a href=\"https://es.gizmodo.com/salgamos-de-dudas-de-una-vez-por-todas-cual-es-el-mejo-1831814320\"><em>Los Simpson</em></a> ha comenzado con una presentaciÃ³n que variaba de alguna forma, haciendo guiÃ±os en muchos casos a acontecimientos <a href=\"https://es.gizmodo.com/asi-es-la-version-de-avengers-endgame-de-los-simpso', 10),
(258, 'https://es.gizmodo.com/asi-son-los-nuevos-portatiles-para-gaming-de-lenovo-ma-1842905269', 'AsÃ­ son los nuevos portÃ¡tiles para gaming de Lenovo: mas baratos y con mucha mÃ¡s baterÃ­a', 'Joanna Nelius', '2020-04-16', '20:14:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--vvwGGS0I--/c_fit,fl_progressive,q_80,w_636/wngy9n4ecp9gr5dlj9do.jpg\"><p><a href=\"https://es.gizmodo.com/el-lenovo-yoga-c740-es-el-mejor-portatil-2-en-1-que-te-1842776549\">Lenovo</a> ha anunciado una actualizaciÃ³n importante de su lÃ­nea para juegos. Esto en principio no es sorprendente, dado que todos los fabricantes estÃ¡n actualizando sus ordenadores portÃ¡tiles para juegos despuÃ©s de que <a href=\"https://gizmodo.com/two-weeks-a', 10),
(259, 'https://es.gizmodo.com/se-filtra-el-nuevo-control-de-xbox-one-inspirado-en-cyb-1842903791', 'Se filtra el nuevo control de Xbox One inspirado en Cyberpunk 2077, y es una preciosidad', 'Eduardo MarÃ­n', '2020-04-16', '18:31:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--YWrmwilv--/c_fit,fl_progressive,q_80,w_636/jiehv1fygqwrglyqlkyi.jpg\"><p><a href=\"https://es.gizmodo.com/cyberpunk-2077-tendra-modo-multijugador-a-diferencia-d-1837879470\"><em>Cyberpunk 2077</em></a> es uno de los <a href=\"https://es.gizmodo.com/los-20-videojuegos-que-mas-esperamos-en-2020-1840950381\">juegos mÃ¡s esperados de este aÃ±o</a> y, en general, de esta generaciÃ³n de consolas. Y para celebrarlo parece que Microsoft trabaja ', 10),
(260, 'https://es.gizmodo.com/crea-imagenes-en-hd-de-la-mision-apolo-13-apilando-foto-1842899209', 'Crean imÃ¡genes en HD de la misiÃ³n Apolo 13 apilando fotogramas de vÃ­deo', 'MatÃ­as S. Zavia', '2020-04-16', '14:41:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--yUtvEc6C--/c_fit,fl_progressive,q_80,w_636/g6q9z0sslvvnfhyetkm7.jpg\"><p>Esta semana <a href=\"https://es.gizmodo.com/la-idea-que-salvo-la-vida-a-los-astronautas-del-apolo-1-1598432163\">cumpliÃ³ 50 aÃ±os</a> la famosa frase â€œHouston, hemos tenido un problemaâ€ que pronunciaron los tripulantes del Apolo 13 antes de abortar misiÃ³n y regresar a la Tierra. Para conmemorarlo, el britÃ¡nico Andy Saunders, conocido por restaurar imÃ¡gene', 10),
(261, 'https://es.gizmodo.com/la-ps5-tendra-un-stock-aun-mas-limitado-en-su-lanzamien-1842897925', 'HabrÃ¡ menos PS5 disponibles durante su lanzamiento y no es por el covid-19. Es por el precio', 'Carlos Zahumenszky', '2020-04-16', '12:22:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--S1IOk6EV--/c_fit,fl_progressive,q_80,w_636/jx9qs0ua6d4bg4u5nes5.jpg\"><p>La PS5 llega estas navidades. De momento no parece que Sony vaya a mover la fecha de lanzamiento de su nueva consola. Lo que sÃ­ parece muy probable es que se pongan menos unidades a la venta. SegÃºn datos de la compaÃ±Ã­a a los que ha tenido acceso <a href=\"https://www.bloomberg.com/news/articles/2020-04-16/sony-is-said-to-plan-limited-playstation-5-output-in-f', 10),
(262, 'https://es.gizmodo.com/la-historia-absurda-de-como-un-genio-se-estrello-en-la-1842897909', 'La historia absurda de cÃ³mo un genio se estrellÃ³ en la misma casa tres veces con dos autos diferentes', 'David Tracy', '2020-04-16', '12:19:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--zACAhIVy--/c_fit,fl_progressive,q_80,w_636/tq5e8vbbubr9ah7whc6b.png\"><p>â€œ<em>... Conductor drogado se empotra en una casa ... tres veces ... con dos vehÃ­culos diferentes</em>â€, escribe la oficina del Ã¡rea de Marin de la <a href=\"https://jalopnik.com/tag/chp\">Patrulla de Carreteras de California</a> en su muro de Facebook antes de continuar: â€œ<em>Los detalles de la llamada fueron tan extraÃ±os que comenzamos nuestra respuesta', 10),
(263, 'https://es.gizmodo.com/devuelve-una-reliquia-que-robo-en-2005-por-temor-a-que-1842897380', 'Devuelve una reliquia que robÃ³ en 2005 por temor a que la pandemia de covid-19 traiga el apocalipsis', 'Carlos Zahumenszky', '2020-04-16', '10:52:00', '\n<img src=\"https://i.kinja-img.com/gawker-media/image/upload/s--YVoKVZ2x--/c_fit,fl_progressive,q_80,w_636/mkoshhhfde6wlj1oc0rm.jpg\"><p>De sufrir una pandemia a salir con una pancarta anunciando el fin de los dÃ­as hay unos cuantos pueblos de distancia, pero un ciudadano anÃ³nimo israelÃ­ ha decidido no correr riesgos y llegar al apocalipsis con la conciencia tranquila. Para eso primero tenÃ­a que devolver una cosita de casi 2.000 aÃ±os de antigÃ¼edad.<br></p>\n<p><a href=\"https://es.gizmodo.com/', 10),
(264, 'http://feeds.weblogssl.com/~r/xataka2/~3/4EAWLbUV-rg/imagenes-alta-resolucion-jamas-tomadas-superficie-solar-revelan-unos-misteriosos-hilos-plasma', 'Las imÃ¡genes de mÃ¡s alta resoluciÃ³n jamÃ¡s tomadas de la superficie solar revelan unos misteriosos \"hilos\" de plasma', 'Santiago Campillo', '2020-04-17', '22:01:02', '\n<p>\n      <img src=\"https://i.blogs.es/673f15/1366_2000-2-/1024_2000.jpg\" alt=\"Las imÃ¡genes de mÃ¡s alta resoluciÃ³n jamÃ¡s tomadas de la superficie solar revelan unos misteriosos \" hilos de plasma>\n    </p>\n    <p>La cÃ¡mara coronal de alta resoluciÃ³n <strong>es uno de los instrumentos mÃ¡s sorprendentes de la astronomÃ­a</strong>: es capaz de fotografiar el Sol con una resoluciÃ³n sin precedentes. Esto nos ha llevado a descubrimientos curiosÃ­simos.</p>\n<!-- BREAK 1 -->\n<p>Entre ellos estÃ¡', 11),
(265, 'https://www.nytimes.com/2020/04/17/us/coronavirus-doctors-dilemmas.html', 'When Duty Calls, and Menaces', 'Jodi Kantor', '2020-04-17', '19:55:32', 'Amid the cheers of gratitude, a painful debate is brewing as doctors grapple with whether to join the front lines of a pandemic.', 12),
(266, 'https://www.nytimes.com/2020/04/16/science/black-hole-sagittarius-a.html', 'Dancing With a Black Hole', 'Dennis Overbye', '2020-04-17', '18:12:06', 'Astronomers described the strange orbit of a star that loops the monster in the Milky Way, offering more evidence for one of Einsteinâ€™s ideas.', 12),
(267, 'https://www.nytimes.com/2020/04/16/smarter-living/coronavirus-introverts-lonely.html', 'Yes, Even Introverts Can Be Lonely Right Now', 'Adam Grant', '2020-04-17', '03:35:29', 'Introverts crave connection, too â€” we just need more boundaries.', 12),
(268, 'https://www.nytimes.com/article/copyrights-trademarks-patents.html', 'The Difference Between Copyrights, Trademarks and Patents', 'Alexander Webb', '2020-04-16', '22:30:07', 'Whether youâ€™re an inventor, a writer or an artist, you need to know what these each mean â€” and which you need to protect your work.', 12),
(269, 'https://www.nytimes.com/2020/04/15/style/self-care/buzz-cut-your-own-hair.html', 'The Ultimate Buzz Cut Guide', 'Sanam Yar', '2020-04-16', '19:56:36', 'Yes, you can use beard clippers. Yes, you will make a mess. Yes, it will grow back. And yes, you can use this to cut someone elseâ€™s hair.', 12),
(270, 'https://www.nytimes.com/2020/04/16/smarter-living/coronavirus-roommate-fight-home.html', 'Roommates or Partner Getting on Your Nerves? Read This', 'Anna Goldfarb', '2020-04-16', '17:02:17', 'Talk about things early and often so they donâ€™t boil over.', 12),
(271, 'https://www.nytimes.com/2020/04/16/books/review/the-plague-albert-camus-coronavirus.html', 'Camusâ€™s Inoculation Against Hate', 'Laura Marris', '2020-04-16', '11:00:05', 'Writing â€œThe Plagueâ€ during the decimation of World War II, Albert Camus used disease as a metaphor for war â€” but also for warâ€™s remedy.', 12),
(272, 'https://www.nytimes.com/2020/04/15/parenting/big-kid/body-image-children.html', 'Your Kids Donâ€™t Have to Inherit Your Body-Image Issues', 'Virginia Sole-Smith', '2020-04-16', '04:13:57', 'Parents who struggle with food and self-image can inadvertently pass along unhealthy behaviors. Hereâ€™s how to avoid it.', 12),
(273, 'https://www.nytimes.com/2020/04/15/smarter-living/learn-to-argue-productively.html', 'Learn to Argue Productively', 'Harry Guinness', '2020-04-16', '03:30:07', 'Arguments donâ€™t have to be heated, explosive moments. As long as everyoneâ€™s in good faith, everyone can learn from one another.', 12),
(274, 'https://www.nytimes.com/2020/04/15/style/working-from-home-setup.html', 'Fix Your Work From Home Office Setup Now', 'John Herrman', '2020-04-15', '18:56:43', 'Whether you are working, looking for work or simply absorbing a new reality, you should be comfortable. Hereâ€™s how to do it with stuff you may already have.', 12),
(275, 'https://www.nytimes.com/2020/04/15/science/physics-neutrino-antimatter-ichikawa-t2k.html', 'Why the Big Bang Produced Something Rather Than Nothing', 'Dennis Overbye', '2020-04-15', '18:26:19', 'How did matter gain the edge over antimatter in the early universe? Maybe, just maybe, neutrinos.', 12),
(276, 'https://www.nytimes.com/2020/04/15/smarter-living/coronavirus-eating-advice.html', 'Eating Is Weird Now. Hereâ€™s How to (Kind of) Get Back to Normal.', 'Tim Herrera', '2020-04-15', '18:02:24', 'If the coronavirus has busted your diet â€” and youâ€™ve busted out the fat pants â€” here are some tips to get back on track.', 12),
(277, 'https://www.nytimes.com/2020/04/14/health/coronavirus-six-feet.html', 'Stay 6 Feet Apart, Weâ€™re Told. But How Far Can Air Carry Coronavirus?', 'Knvul Sheikh, James Gorman and Kenneth Chang', '2020-04-15', '10:24:38', 'Most of the big droplets travel a mere six feet. The role of tiny aerosols is the â€œtrillion-dollar question.â€', 12),
(278, 'https://www.nytimes.com/2020/04/14/well/family/coronavirus-quarantine-board-games-videoconferencing.html', 'Classic Board Games With a Touch of Tech', 'Catherine Newman', '2020-04-15', '00:16:23', 'How to use video conferencing to play traditional, real-life board games with people who are sheltering in different places.', 12),
(279, 'https://www.nytimes.com/2020/04/09/movies/hulu-indie-movies.html', 'Watch These 12 Underseen Indie Movies on Hulu', 'Scott Tobias', '2020-04-09', '20:01:24', 'The streaming service has become a reliable destination for independent films. Here are some of our favorites.', 12),
(280, 'https://www.nytimes.com/puzzles/spelling-bee', 'Try Spelling Bee', 'The New York Times', '2020-03-24', '01:44:17', 'Puzzle throughout the day to see how many words you can find.', 12),
(281, 'https://www.nytimes.com/crosswords', 'The Crossword, Vertex and More', 'The New York Times', '2020-03-24', '01:44:17', 'Solve the daily puzzle edited by Will Shortz, or try out other games like the Mini and Letter Boxed.', 12),
(282, 'https://www.nytimes.com/puzzles/tiles', 'Try Tiles', 'The New York Times', '2020-03-24', '01:44:17', 'Our soothing matching game may help you de-stress.', 12);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pagina`
--

CREATE TABLE `pagina` (
  `id` int(50) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `subtitulo` varchar(100) NOT NULL,
  `url` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `pagina`
--

INSERT INTO `pagina` (`id`, `nombre`, `subtitulo`, `url`) VALUES
(10, 'Gizmodo en Español', 'Las ultimas noticias en tecnología, ciencia y cultura digital.', 'https://es.gizmodo.com'),
(11, 'Xataka', 'Publicación de noticias sobre gadgets y tecnología. Últimas tecnologías en electrónica de consumo y ', 'http://feeds.weblogssl.com/xataka2.xml'),
(12, 'NYT &gt; Top Stories', '', 'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `articulo`
--
ALTER TABLE `articulo`
  ADD PRIMARY KEY (`id`),
  ADD KEY `pagina` (`id_pagina`);
ALTER TABLE `articulo` ADD FULLTEXT KEY `fullqr` (`titulo`,`autor`,`descripcion`);

--
-- Indices de la tabla `pagina`
--
ALTER TABLE `pagina`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `articulo`
--
ALTER TABLE `articulo`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=283;

--
-- AUTO_INCREMENT de la tabla `pagina`
--
ALTER TABLE `pagina`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `articulo`
--
ALTER TABLE `articulo`
  ADD CONSTRAINT `articulo_ibfk_1` FOREIGN KEY (`id_pagina`) REFERENCES `pagina` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
